### PR TITLE
Update thinc for 6.10.0

### PR DESCRIPTION
**Pull request by honnibal**
If all checks pass we're going to be promoting `spacy-nightly-2.0.0a19` to `spacy-2.0.0rc0` :tada: 

Getting the updated dependencies onto conda.

### CODE REVIEW

**Comment by rmax** [comment]
The recipe is missing the changes in requirements:
```
             install_requires=[
                 'wrapt',
                 'numpy>=1.7',
-                'murmurhash>=0.26,<0.27',
+                'murmurhash>=0.28,<0.29',
                 'cymem>=1.30,<1.32',
                 'preshed>=1.0.0,<2.0.0',
                 'tqdm>=4.10.0,<5.0.0',
                 'cytoolz>=0.8,<0.9',
                 'plac>=0.9.6,<1.0.0',
                 'six>=1.10.0,<2.0.0',
                 'dill',
-                'pathlib>=1.0.0,<2.0.0'
+                'termcolor',
+                'pathlib>=1.0.0,<2.0.0',
+                'msgpack-python',
+                'msgpack-numpy'
             ],
```

**Comment by honnibal** [comment]
Yep, just noticed --- trying again!

**Comment by rmax** [comment]
We are forgetting to update numpy pinning following latest conda-forge conventions. Please apply this changes:

```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index c6f63f8..5e70059 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -27,13 +27,16 @@ requirements:
     - msinttypes  # [win and py27]
     - python
     - setuptools
-    - numpy x.x
-    - numpy >=1.7
+    # Pin numpy at build time with the minimum version available.
+    - numpy 1.8.*   # [not (win and (py35 or py36))]
+    - numpy 1.9.*   # [win and py35]
+    - numpy 1.11.*  # [win and py36]
 
   run:
     - python
-    - numpy x.x
-    - numpy >=1.7
+    - numpy >=1.8   # [not (win and (py35 or py36))]
+    - numpy >=1.9   # [win and py35]
+    - numpy >=1.11  # [win and py36]
     - murmurhash >=0.26,<0.27
     - cymem >=1.30,<1.32
     - preshed >=1.0.0,<2.0.0
```

Commit and then regenerate the feedstock:
```cli
thinc-feedstock$ conda install -nroot conda-smithy
thinc-feedstock$ conda-smithy regenerate -c
```

**Comment by honnibal** [comment]
Can't say I follow all the subtleties of that --- but done!

**Pull request merged**
